# CI script for KoraOS on Gitlab
# -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

build:
  stage: build
  before_script:
    - apt-get update
    - apt-get install -y nasm
  script:
    - make clean
    - make
  artifacts:
    paths:
      - lib/libc.so

test:
  stage: test
  before_script:
    - apt-get update
    - apt-get install -y nasm
  script:
    - make clean
    - make check
    # - make coverage NOSCALL=y GCOV=y
  coverage: /(\d+(\.\d+)?)% \(\d+ of \d+ lines\)/

deploy:
  stage: deploy
  needs:
    - job: build
      artifacts: true
  only:
    refs:
      - /v\d+\.\d+\.\d+/
  script:
    - echo "Send to repository"
    - size lib/libc.so
  release:
    name: "$CI_COMMIT_TAG"
    description:  'My awesome release'
    tag_name: "$CI_COMMIT_TAG"


# -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

# build_kora:
#   stage: build
#   image: axfab/kora-gcc:latest
#   script:
#     - mkdir build
#     - cd build && ../configure --target=i386-kora
#     - cd build && make
#   artifacts:
#     paths:
#       - build/lib/libc.so
