# CI script for KoraOS on Gitlab
# -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

build:
  stage: build
  script:
    - make clean
    - make
  artifacts:
    paths:
      - lib/libc.so

test:
  stage: test
  script:
    - make clean
    - make check
    - make coverage
  coverage: /(\d+)(\.\d+)?% \(\d+ of \d+ lines\)/

deploy:
  stage: deploy
  needs:
    - job: build
      artifacts: true
  only:
    refs:
      - /v\d+\.\d+\.\d+/
  script:
    - echo "Send to repository"
    - size lib/libc.so
  release:
    name: "$CI_COMMIT_TAG"
    description:  'My awesome release'
    tag_name: "$CI_COMMIT_TAG"


# -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

build_kora:
  stage: build
  image: axfab/kora-gcc:latest
  script:
    - mkdir build
    - cd build && ../configure --target=i386-kora
    - cd build && make
  artifacts:
    paths:
      - build/lib/libc.so
