name: CI

on:
  push:
    branches: [ develop, master ]
  pull_request:
    branches: [ develop, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install nasm
      run: sudo apt-get install -y nasm
    - name: make
      run: make

  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install nasm
      run: sudo apt-get install -y nasm
    - name: make check
      run: make check

